antvis/AVA

- README.md
- zh-CN/README.zh-CN.md
> feat: add kanaries links

- packages/datawizard/analyzer/__tests__/index.test.ts
- packages/datawizard/analyzer/src/utils.ts
> fix: error when date is null for #18

- .eslintrc
- HOWITWORKS.md
- common/reviews/api/chart-advisor.api.md
- demo/AutoChartTest.tsx
- demo/FindInsightTest.tsx
- demo/PipelineTest.tsx
- demo/app.tsx
- demo/index.less
- lerna.json
- package.json
- packages/chart-advisor/package.json
- packages/chart-advisor/src/advisor.ts
- packages/chart-advisor/src/auto-plot.ts
- packages/chart-advisor/src/chartLibMapping/G2Plot.ts
- packages/chart-advisor/src/chartLibMapping/index.ts
- packages/chart-advisor/src/config-panel.ts
- packages/chart-advisor/src/index.ts
- packages/chart-advisor/src/util.ts
split pipeline of chart-advisor:
-  dataToDataProps
- dataPropsToSpecs
- specToLibConfig
> Split pipeline data

- lerna.json
- packages/chart-advisor/package.json
- packages/datawizard/analyzer/package.json
- packages/datawizard/transform/.npmignore
- packages/datawizard/transform/package.json
- packages/datawizard/transform/webpack.config.js
> dw-transform pack

- README.md
- zh-CN/README.zh-CN.md
* add link to development wiki page on README
> docs(readme): dev wiki

- packages/chart-advisor/src/advice-pipeline/dataprops-to-specs.ts
- packages/chart-advisor/src/advice-pipeline/index.ts
- packages/chart-advisor/src/advice-pipeline/interface.ts
- packages/chart-advisor/src/advice-pipeline/spec-to-libconfig.ts
- packages/chart-advisor/src/types/index.d.ts
* 声明文件避免 data-set 引用包报错；
* 修复部分 api extractor warning
> chore: declare untypes modules

- .babelrc
- demo/PipelineTest.tsx
- demo/app.tsx
- demo/index.less
- demo/table.less
- package.json
- webpack.config.js
使用 antd 优化 demo ui 页面
~~ant design pro 作为独立项目对于依赖外部 packages 内的代码热更新效果不佳，所以还是简单写个页面样式~~
TODO: 之后可以逐渐把各页面的组件换成 antd
> feat: optimize demo ui

- packages/ava-site/gatsby-browser.js
- packages/ava-site/package.json
> chore: improve site istart

- packages/knowledge/__tests__/pack.test.ts
- packages/knowledge/src/base.ts
- packages/knowledge/src/i18n/zh-CN.ts
add radial bar chart and Chinese translation.
> feat(CKB): add radial bar chart spec

- packages/knowledge/src/base.ts
add ordinal dataPres in bar/column/pie charts as discussed in #100
> feat(CKB): add ordinal in bar/column/pie charts

- common/reviews/api/chart-advisor.api.md
- packages/ava-site/docs/api/chart-advisor/dataToDataProps.en.md
- packages/ava-site/docs/api/chart-advisor/dataToDataProps.zh.md
- packages/chart-advisor/__tests__/unit/pipeline/data-to-dataprops.test.ts
- packages/chart-advisor/src/advice-pipeline/data-to-dataprops.ts
- packages/chart-advisor/src/advice-pipeline/index.ts
- packages/chart-advisor/src/auto-plot.ts
> feat(chart-advisor): select specific fields to pipeline

- package.json
> chore: fix lint and bootstrap when pre commit

- demo/AutoChartTest.tsx
- demo/auto-chart.tsx
- packages/ava-site/docs/api/chart-advisor/autoChart.en.md
- packages/ava-site/docs/api/chart-advisor/autoChart.zh.md
- packages/chart-advisor/src/auto-chart.ts
- packages/chart-advisor/src/config-panel.ts
- packages/chart-advisor/src/i18n/index.ts
- packages/chart-advisor/src/i18n/locales/en_US.ts
- packages/chart-advisor/src/i18n/locales/index.ts
- packages/chart-advisor/src/i18n/locales/zh_CN.ts
- packages/chart-advisor/src/index.ts
- packages/chart-advisor/src/mock-panel.ts
- packages/chart-advisor/src/style.ts
- packages/chart-advisor/src/toolbar.ts
Add i18n option for toolbar, config panel, mock panel.
> fix(chart-advisor): add i18n option

- packages/chart-advisor/src/i18n/locales/zh_CN.ts
> fix(chart-advisor): add some i18n words

- packages/chart-advisor/__tests__/unit/pipeline/dataprops-to-advices.test.ts
- packages/chart-advisor/src/advice-pipeline/dataprops-to-advices.ts
- packages/chart-advisor/src/advice-pipeline/index.ts
- packages/chart-advisor/src/advice-pipeline/interface.ts
- packages/chart-advisor/src/index.ts
- packages/chart-advisor/src/rules/rules.ts
> feat(chart-advisor): support custom chart knowledge

- packages/chart-advisor/src/i18n/locales/en_US.ts
- packages/chart-advisor/src/i18n/locales/zh_CN.ts
- packages/chart-advisor/src/mock-panel.ts
> fix(chart-advisor): adjust i18n locales

- demo/Linter/index.tsx
- demo/LinterExtend/ChartVL.tsx
- demo/LinterExtend/G2PlotWrapper.tsx
- demo/LinterExtend/LinterWrapper.tsx
- demo/LinterExtend/SpecWrapper.tsx
- demo/LinterExtend/demos/column.ts
- demo/LinterExtend/demos/index.ts
- demo/LinterExtend/demos/wrongColumn.ts
- demo/LinterExtend/g2-render.ts
- demo/LinterExtend/index.less
- demo/LinterExtend/index.module.less
- demo/LinterExtend/index.tsx
- demo/app.tsx
- package.json
- packages/chart-linter/__tests__/unit/adaptor/lib-to-spec.test.ts
- packages/chart-linter/__tests__/unit/adaptor/spec-to-lib.test.ts
- packages/chart-linter/src/adaptor/index.ts
- packages/chart-linter/src/adaptor/interface.ts
- packages/chart-linter/src/adaptor/lib-to-spec/index.ts
- packages/chart-linter/src/adaptor/spec-to-lib/index.ts
- packages/chart-linter/tsconfig.json
- webpack.config.js
- Initialize adaptor and linterExtendDemo.
- Add less module to linterExtendDemo.
> feat(chart-linter): init adaptor and linterExtendDemo

- demo/LinterExtend/G2PlotWrapper.tsx
- demo/LinterExtend/index.tsx
- packages/chart-linter/src/index.ts
Export adaptor's function and interface.
> fix(chart-linter): export adaptor's function and interface

- jest.config.js
> chore: longer test timeout

- packages/chart-advisor/src/auto-chart/auto-chart.ts
- packages/chart-advisor/src/auto-chart/auto-plot.ts
- packages/chart-advisor/src/i18n/locales/en_US.ts
- packages/chart-advisor/src/i18n/locales/zh_CN.ts
- packages/chart-linter/.gitignore
- packages/chart-linter/package.json
i18n for statistic title in pie chart
> fix(auto-chart): add pie statistic i18n patch

- packages/datawizard/random/__tests__/text-random.test.ts
- packages/datawizard/random/src/text-random.ts
> fix: generated phone numbers should not be real

- packages/chart-linter/package.json
> chore(chart-linter): update package.json

- README.md
- packages/chart-linter/README.md
- packages/chart-linter/zh-CN/README.zh-CN.md
> docs(chart-linter): update README

- packages/ava-site/docs/guide/chart-linter/intro.en.md
- packages/ava-site/docs/guide/chart-linter/intro.zh.md
- packages/ava-site/site/locale.json
> site docs and texts

- packages/chart-advisor/src/auto-chart/auto-chart.ts
> fix: dummy plot i18n patch

- packages/ava-site/docs/guide/ckb/intro.en.md
- packages/ava-site/docs/guide/ckb/intro.zh.md
> feat: add a demo in CKB guide

- packages/chart-advisor/src/auto-chart/config-panel.ts
> fix:  'postmessage' error

- demo/src/demos/SmartBoard/ChartSamples/chartSample1.ts
- demo/src/demos/SmartBoard/ChartSamples/chartSample2.ts
- demo/src/demos/SmartBoard/ChartSamples/index.ts
- demo/src/demos/SmartBoard/Page/ChartView.tsx
- demo/src/demos/SmartBoard/Page/Dashboard.tsx
- demo/src/demos/SmartBoard/Page/Toolbar.tsx
- demo/src/demos/SmartBoard/Page/index.less
- demo/src/demos/SmartBoard/Page/index.tsx
- demo/src/demos/SmartBoard/index.tsx
- demo/src/demos/SmartBoard/utils/aggregate.ts
- demo/src/demos/SmartBoard/utils/chartInfo2Config.ts
- demo/src/demos/SmartBoard/utils/g2plotRender.ts
- demo/src/demos/SmartBoard/utils/index.ts
- demo/src/manifest.tsx
> feat(SmartBoard): add smartboard demo

- demo/package.json
- demo/src/demos/ChartAdvisor/Advisor/AdviceCard.tsx
- demo/src/demos/ChartAdvisor/Advisor/AdvisorPanel.tsx
- demo/src/demos/ChartAdvisor/CA/CACard.tsx
- demo/src/demos/ChartAdvisor/CA/CAPanel.tsx
- demo/src/demos/ChartAdvisor/Chart.tsx
- demo/src/demos/ChartAdvisor/ChartAdvisor.tsx
- demo/src/demos/ChartAdvisor/Linter/LintCard.tsx
- demo/src/demos/ChartAdvisor/Linter/LinterPanel.tsx
- demo/src/demos/ChartAdvisor/data.json
- demo/src/demos/ChartAdvisor/index.tsx
- demo/src/manifest.tsx
> feat(CA): simple demo of CA

- packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
- packages/chart-advisor/src/linter/index.ts
- packages/chart-advisor/src/ruler/concepts/rule.ts
- packages/chart-advisor/src/ruler/rules/aggregation-single-row.ts
- packages/chart-advisor/src/ruler/rules/all-can-be-table.ts
- packages/chart-advisor/src/ruler/rules/bar-series-qty.ts
- packages/chart-advisor/src/ruler/rules/data-check.ts
- packages/chart-advisor/src/ruler/rules/data-field-qty.ts
- packages/chart-advisor/src/ruler/rules/diff-pie-sector.ts
- packages/chart-advisor/src/ruler/rules/landscape-or-portrait.ts
- packages/chart-advisor/src/ruler/rules/limit-series.ts
- packages/chart-advisor/src/ruler/rules/line-field-time-ordinal.ts
- packages/chart-advisor/src/ruler/rules/no-redundant-field.ts
- packages/chart-advisor/src/ruler/rules/nominal-enum-combinatorial.ts
- packages/chart-advisor/src/ruler/rules/purpose-check.ts
- packages/chart-advisor/src/ruler/rules/series-qty-limit.ts
- packages/chart-advisor/src/ruler/rules/x-axis-line-fading.ts
> feat(advisor): add rule trigger

- packages/lite-insight/src/visualization/annotation.ts
- packages/lite-insight/src/visualization/util.ts
> feat(lite-insight): update annotation

- demo/src/demos/ChartAdvisor/Advisor/AdvisorPanel.tsx
- demo/src/demos/ChartAdvisor/CA/CAPanel.tsx
- demo/src/demos/ChartAdvisor/Linter/LinterPanel.tsx
- packages/chart-advisor/__tests__/ckb.test.ts
- packages/chart-advisor/__tests__/dataprops.test.ts
- packages/chart-advisor/__tests__/index.test.ts
- packages/chart-advisor/__tests__/rule.test.ts
- packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
- packages/chart-advisor/src/advisor/index.ts
- packages/chart-advisor/src/chart-advisor/index.ts
- packages/chart-advisor/src/linter/index.ts
- packages/chart-advisor/src/ruler/concepts/rule.ts
> feat(CA): customized dataprops input

- packages/data-wizard/__tests__/analyzer/index.test.ts
- packages/data-wizard/__tests__/analyzer/is-date.test.ts
- packages/data-wizard/__tests__/dataset/data-frame.test.ts
- packages/data-wizard/__tests__/statistics/index.test.ts
- packages/data-wizard/__tests__/utils/index.test.ts
- packages/data-wizard/src/analyzer/index.ts
- packages/data-wizard/src/dataset/data-frame.ts
- packages/data-wizard/src/dataset/types.ts
- packages/data-wizard/src/dataset/utils.ts
- packages/data-wizard/src/statistics/caches.ts
- packages/data-wizard/src/statistics/index.ts
- packages/data-wizard/src/utils/index.ts
> feat(DW): add analyzer, statistics and utils tests

- packages/chart-advisor/src/advisor/advice-pipeline/spec-mapping.ts
- packages/data-wizard/__tests__/dataset/data-frame.test.ts
- packages/data-wizard/__tests__/dataset/series.test.ts
- packages/data-wizard/src/analyzer/index.ts
- packages/data-wizard/src/dataset/base-frame.ts
- packages/data-wizard/src/dataset/data-frame.ts
- packages/data-wizard/src/dataset/series.ts
- packages/data-wizard/src/dataset/utils.ts
- packages/data-wizard/src/index.ts
- packages/data-wizard/src/statistics/index.ts
- packages/data-wizard/src/utils/index.ts
Abbreviation may make confusion. I change DW's abbr words to complete spelling following other AVA packages.
> refactor(DW): change DW abbr to complete spelling

- demo/src/demos/LiteInsight/AutoInsight.tsx
- packages/lite-insight/src/algorithms/pettitt-test.ts
- packages/lite-insight/src/constant.ts
- packages/lite-insight/src/insights/checkers.ts
- packages/lite-insight/src/insights/extractors/categoryOutlier.ts
- packages/lite-insight/src/insights/extractors/changePoint.ts
- packages/lite-insight/src/insights/extractors/timeSeriesOutlier.ts
- packages/lite-insight/src/insights/extractors/trend.ts
- packages/lite-insight/src/insights/index.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/pipeline/homogeneous.ts
- packages/lite-insight/src/pipeline/index.ts
- packages/lite-insight/src/pipeline/insight.ts
- packages/lite-insight/src/pipeline/preprocess.ts
- packages/lite-insight/src/pipeline/util.ts
- packages/lite-insight/src/utils/aggregate.ts
- packages/lite-insight/src/visualization/annotation.ts
- packages/lite-insight/src/visualization/description.ts
- packages/lite-insight/src/visualization/index.ts
- packages/lite-insight/src/visualization/util.ts
As defined in 《_MetaInsight_》, Homogeneous Data Pattern （HDP） is a set of type-induced data patterns derived from an HDS(Homogeneous data scope).
A data scope _ds_ ⟨subspace, breakdown, measure⟩ is a 3-tuple, so there are three ways to derive data scopes that are homogeneous (i.e., the data scopes that only differ from _ds_ by one element under certain constraints). 
Two data scope extending strategies in this PR: 
An HDP can partition into different classes, CommSets and Exceptions. Each element in CommSet is denoted as a commonness (a collection of data patterns that share the same type and highlight). Exceptions denote the remaining data patterns that do not belong to any commonness(es).
Demo:
> feat(lite-insight): homogeneous pattern

- packages/chart-advisor/__tests__/rule.test.ts
> fix(CA): fix bug in test

- demo/src/demos/SmartBoard/ChartSamples/chartSample1.ts
- demo/src/demos/SmartBoard/ChartSamples/chartSample2.ts
- demo/src/demos/SmartBoard/ChartSamples/index.ts
- demo/src/demos/SmartBoard/Page/ChartView.tsx
- demo/src/demos/SmartBoard/Page/Dashboard.tsx
- demo/src/demos/SmartBoard/Page/Toolbar.tsx
- demo/src/demos/SmartBoard/Page/index.less
- demo/src/demos/SmartBoard/Page/index.tsx
- packages/smart-board/package.json
- packages/smart-board/src/interfaces.ts
> fix(style): fix the UI of title view

- demo/src/demos/ChartAdvisor/Advisor/AdvisorPanel.tsx
- packages/chart-advisor/package.json
- packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
- packages/chart-advisor/src/advisor/advice-pipeline/interface.ts
> feat(CA): config primary color

- packages/lite-insight/src/visualization/annotation.ts
- packages/lite-insight/src/visualization/index.ts
> feat: homogeneous insight annotation

- packages/chart-advisor/package.json
> chore(CA): limit-size

- packages/chart-advisor/__tests__/index.test.ts
- packages/chart-advisor/src/advisor/index.ts
> fix(CA): bugs when no input fields

- sites/ava-site/.eslintrc.js
- sites/ava-site/gatsby-browser.js
- sites/ava-site/gatsby-config.js
- sites/ava-site/jest.config.js
- sites/ava-site/package.json
> chore(site): revive ava site

- packages/auto-chart/package.json
- packages/auto-chart/rollup.config.js
> fix(auto-chart): add auto-chart build set

- packages/chart-advisor/API.md
- packages/chart-advisor/README.md
> docs(CA): readme and api

- packages/data-wizard/__tests__/analyzer/is-date.test.ts
- packages/data-wizard/__tests__/dataset/data-frame.test.ts
- packages/data-wizard/__tests__/dataset/series.test.ts
- packages/data-wizard/__tests__/dataset/utils.test.ts
- packages/data-wizard/__tests__/random/color-random.test.ts
- packages/data-wizard/__tests__/random/date-time-random.test.ts
- packages/data-wizard/__tests__/random/text-random.test.ts
- packages/data-wizard/__tests__/random/web-random.test.ts
- packages/data-wizard/__tests__/utils/index.test.ts
- packages/data-wizard/src/analyzer/is-date.ts
- packages/data-wizard/src/random/basic-random.ts
- packages/data-wizard/src/random/color-random.ts
- packages/data-wizard/src/random/color-utils.ts
- packages/data-wizard/src/random/datetime-random.ts
- packages/data-wizard/src/random/location-random.ts
- packages/data-wizard/src/random/text-random.ts
- packages/data-wizard/src/random/utils.ts
- packages/data-wizard/src/random/web-random.ts
> feat(DW): improve tests

- demo/src/demos/LiteInsight/AutoInsight.tsx
- packages/lite-insight/package.json
- packages/lite-insight/src/algorithms/BayesianChangePoint/BayesianChangePoint.ts
- packages/lite-insight/src/algorithms/BayesianChangePoint/Gamma.ts
- packages/lite-insight/src/algorithms/BayesianChangePoint/PDF.ts
- packages/lite-insight/src/algorithms/buishand-u.ts
- packages/lite-insight/src/algorithms/index.ts
- packages/lite-insight/src/algorithms/pettitt-test.ts
- packages/lite-insight/src/insights/extractors/changePoint.ts
add two change-point detection methods: [Bayesian ChangePoint](https://arxiv.org/pdf/0710.3742.pdf),  Buishad U statistics test
> feat(insight): add change-point detection methods

- packages/lite-insight/src/algorithms/buishand-u.ts
> Fix liteinsight build error

- demo/src/demos/LiteInsight/AutoInsight.tsx
- packages/lite-insight/src/constant.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/pipeline/insight.ts
A change of score formula: 【Significance * Impact】 => 【Significance * (1 - weight) + Impact * weight】
> refactor(lite-insight): Insight score formula

- packages/lite-insight/README.md
- packages/lite-insight/README.zh-CN.md
- sites/ava-site/docs/api/lite-insight.en.md
- sites/ava-site/docs/api/lite-insight.zh.md
- sites/ava-site/package.json
> feat(insights): add api doc & readme

- packages/smart-board/package.json
revert pkg.json of sb that has been edited by other rebase operations
> feat(SB): re-add scripts & li/dw depencencies

- packages/smart-board/src/components/defaultChartView.tsx
- sites/ava-site/docs/api/smart-color/colorComputation.en.md
- sites/ava-site/docs/api/smart-color/colorComputation.zh.md
- sites/ava-site/docs/api/smart-color/colorConversion.en.md
- sites/ava-site/docs/api/smart-color/colorConversion.zh.md
- sites/ava-site/docs/api/smart-color/evaluators.en.md
- sites/ava-site/docs/api/smart-color/evaluators.zh.md
- sites/ava-site/docs/api/smart-color/extractors.en.md
- sites/ava-site/docs/api/smart-color/extractors.zh.md
- sites/ava-site/docs/api/smart-color/generators.en.md
- sites/ava-site/docs/api/smart-color/generators.zh.md
- sites/ava-site/docs/api/smart-color/intro.en.md
- sites/ava-site/docs/api/smart-color/intro.zh.md
- sites/ava-site/docs/api/smart-color/optimizers.en.md
- sites/ava-site/docs/api/smart-color/optimizers.zh.md
- sites/ava-site/docs/api/smart-color/simulators.en.md
- sites/ava-site/docs/api/smart-color/simulators.zh.md
- sites/ava-site/docs/guide/smart-color/intro.en.md
- sites/ava-site/docs/guide/smart-color/intro.zh.md
- sites/ava-site/gatsby-config.js
> docs(color): add docs for smart-color

- packages/smart-board/package.json
- packages/smart-board/src/components/defaultBoard.tsx
- packages/smart-board/src/components/defaultChartView.tsx
- packages/smart-board/src/components/defaultSelector.tsx
- packages/smart-board/src/components/defaultToolbar.tsx
- packages/smart-board/src/components/index.ts
- packages/smart-board/src/index.ts
- packages/smart-board/src/interfaces.ts
- packages/smart-board/src/utils/smartBoardConfig.ts
> fix(SB): move interfaces to fix demo warnings

- .gitignore
- packages/auto-chart/package.json
- packages/auto-chart/rollup.config.js
> chore(auto-chart): add bundle analysis

- sites/ava-site/docs/guide/lite-insight/intro.en.md
- sites/ava-site/docs/guide/lite-insight/intro.zh.md
- sites/ava-site/gatsby-config.js
- add guide doc
- add pipeline illustration in readme
> feat(insight): add guide doc

- sites/ava-site/examples/chart-advisor/advise-and-lint/demo/ca-steps.jsx
- sites/ava-site/examples/chart-advisor/advise-and-lint/demo/custom-ckb-rules-ca.jsx
- sites/ava-site/examples/chart-advisor/advise-and-lint/demo/meta.json
> feat(site): ca custom-ckb-rules demo

- sites/ava-site/docs/api/data-wizard/statistics.en.md
- sites/ava-site/docs/api/data-wizard/statistics.zh.md
- sites/ava-site/examples/data-wizard/statistics/demo/complex.jsx
- sites/ava-site/examples/data-wizard/statistics/demo/meta.json
> feat(DW): add statistics-complex objects demo

- sites/ava-site/examples/chart-advisor/relation/demo/meta.json
- sites/ava-site/examples/chart-advisor/relation/demo/sankey.jsx
- sites/ava-site/examples/chart-advisor/relation/demo/tree.jsx
- add graph demo thumbnails
- improve and fix graph demo
> fix(demo): add graph demo thumbnails & improve demo

- sites/ava-site/examples/chart-advisor/advise-and-lint/demo/ca-steps.jsx
- sites/ava-site/examples/chart-advisor/advise-and-lint/demo/meta.json
- sites/ava-site/examples/chart-advisor/advisor-only/demo/meta.json
- sites/ava-site/examples/chart-advisor/linter-only/demo/meta.json
> fix(site): ca demo screenshots

- sites/ava-site/examples/chart-advisor/advise-and-lint/API.en.md
- sites/ava-site/examples/chart-advisor/advise-and-lint/API.zh.md
- sites/ava-site/examples/chart-advisor/advisor-only/API.en.md
- sites/ava-site/examples/chart-advisor/advisor-only/API.zh.md
- sites/ava-site/examples/chart-advisor/linter-only/API.en.md
- sites/ava-site/examples/chart-advisor/linter-only/API.zh.md
- sites/ava-site/examples/chart-advisor/relation/API.en.md
- sites/ava-site/examples/chart-advisor/relation/API.zh.md
fix the api  markdown link in site demo
> fix(site): fix the api  markdown link in site demo

- packages/lite-insight/src/insights/extractors/lowVariance.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/visualization/annotation.ts
- packages/lite-insight/src/visualization/index.ts
> feat(LI): add annotation for low-variance

- demo/src/demos/LiteInsight/AutoInsight.tsx
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/pipeline/extract.ts
- sites/ava-site/docs/api/lite-insight/auto-insights.en.md
- sites/ava-site/docs/api/lite-insight/auto-insights.zh.md
ignoreSubspace |  `boolean` | Whether to close the search for subspaces. | `false`
> feat(LI): add ignoreSubspace option

- packages/chart-advisor/__tests__/rule.test.ts
- packages/chart-advisor/src/advisor/index.ts
- packages/smart-board/__tests__/unit/SmartBoard/index.test.ts
> test: fix old test cases

- demo/src/demos/LiteInsight/AutoInsight.tsx
- packages/lite-insight/src/narrative/strategy/subjects-desc.ts
- sites/ava-site/examples/lite-insight/custom/demo/homogeneous.jsx
- sites/ava-site/examples/lite-insight/custom/demo/impact.jsx
- sites/ava-site/examples/lite-insight/custom/demo/insight-type.jsx
- sites/ava-site/examples/lite-insight/visualization/demo/index.jsx
- sites/ava-site/package.json
> fix(LI): adjust insightCard height in demo

- demo/.umirc.ts
- demo/package.json
- demo/src/global.css
- demo/src/pages/index.less
- packages/auto-chart/README.md
- packages/auto-chart/README.zh-CN.md
- packages/auto-chart/package.json
- packages/auto-chart/rollup.config.js
- packages/auto-chart/src/ConfigPanel/index.tsx
- packages/auto-chart/src/index.less
> auto-chart build & readme docs

- packages/data-wizard/README.md
- packages/data-wizard/README.zh-CN.md
- sites/ava-site/docs/api/chart-advisor/advice.en.md
- sites/ava-site/docs/api/chart-advisor/advice.zh.md
- sites/ava-site/docs/api/data-wizard/graph-data.en.md
- sites/ava-site/docs/api/data-wizard/graph-data.zh.md
- sites/ava-site/docs/guide/data-wizard/intro.en.md
- sites/ava-site/docs/guide/data-wizard/intro.zh.md
Graph data related api and intro
> docs(dw): add graph data related api and intro

- sites/ava-site/docs/guide/intro.en.md
- sites/ava-site/docs/guide/intro.zh.md
- sites/ava-site/docs/guide/migrate.en.md
- sites/ava-site/docs/guide/migrate.zh.md
> docs(auto-chart): migrate of v1 to v2

- sites/ava-site/docs/guide/migrate.en.md
- sites/ava-site/docs/guide/migrate.zh.md
> docs(DW): migrate of v1 to v2

- .markdownlint.json
- packages/chart-advisor/src/ruler/rules/bar-series-qty.ts
- packages/chart-advisor/src/ruler/rules/bar-without-axis-min.ts
- packages/chart-advisor/src/ruler/rules/data-check.ts
- packages/chart-advisor/src/ruler/rules/data-field-qty.ts
- packages/chart-advisor/src/ruler/rules/diff-pie-sector.ts
- packages/chart-advisor/src/ruler/rules/landscape-or-portrait.ts
- packages/chart-advisor/src/ruler/rules/limit-series.ts
- packages/chart-advisor/src/ruler/rules/line-field-time-ordinal.ts
- packages/chart-advisor/src/ruler/rules/no-redundant-field.ts
- packages/chart-advisor/src/ruler/rules/nominal-enum-combinatorial.ts
- packages/chart-advisor/src/ruler/rules/purpose-check.ts
- packages/chart-advisor/src/ruler/rules/series-qty-limit.ts
- packages/chart-advisor/src/ruler/rules/x-axis-line-fading.ts
- packages/smart-board/package.json
- sites/ava-site/docs/common/style.md
- sites/ava-site/docs/guide/chart-advisor/ChartAdvisor.en.md
- sites/ava-site/docs/guide/chart-advisor/ChartAdvisor.zh.md
- sites/ava-site/docs/guide/rules/rules.en.md
- sites/ava-site/docs/guide/rules/rules.zh.md
- sites/ava-site/gatsby-config.js
> docs(site): add rules doc and fix some mistakes

- packages/chart-advisor/src/ruler/rules/bar-without-axis-min.ts
> fix(CA): add x-axis minimum detection for bar chart

- README.md
- packages/ckb/API.md
- packages/ckb/README.md
- packages/ckb/zh-CN/README.zh-CN.md
- sites/ava-site/docs/api/ckb/CKBJson.en.md
- sites/ava-site/docs/api/ckb/CKBJson.zh.md
- sites/ava-site/docs/api/ckb/CKBOptions.en.md
- sites/ava-site/docs/api/ckb/CKBOptions.zh.md
- sites/ava-site/docs/api/ckb/intro.en.md
- sites/ava-site/docs/api/ckb/intro.zh.md
- sites/ava-site/docs/api/ckb/types.en.md
- sites/ava-site/docs/api/ckb/types.zh.md
- sites/ava-site/docs/guide/ckb/intro.en.md
- sites/ava-site/docs/guide/ckb/intro.zh.md
- sites/ava-site/docs/guide/intro.en.md
- sites/ava-site/docs/guide/intro.zh.md
- zh-CN/README.zh-CN.md
> docs: change knowledge to ckb

- sites/ava-site/docs/api/data-wizard/data-frame.en.md
- sites/ava-site/docs/api/data-wizard/data-frame.zh.md
> docs(dw): add columnTypes description

- demo/.umirc.ts
- demo/src/manifest.tsx
- package.json
- packages/lite-insight/__tests__/extractors/correlation.test.ts
- packages/lite-insight/src/constant.ts
- packages/lite-insight/src/insights/checkers.ts
- packages/lite-insight/src/insights/extractors/correlation.ts
- packages/lite-insight/src/insights/index.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/narrative/generator/insight.ts
- packages/lite-insight/src/narrative/strategy/correlation.ts
- packages/lite-insight/src/narrative/strategy/index.ts
- packages/lite-insight/src/narrative/strategy/majority.ts
- packages/lite-insight/src/narrative/strategy/trend.ts
- packages/lite-insight/src/pipeline/extract.ts
- packages/lite-insight/src/visualization/annotation.ts
- packages/lite-insight/src/visualization/index.ts
- rollup.config.js
- Add `correlation` insight
- add dev dep @rollup/plugin-json
TODO:  Subject description for 1M * 1M
> feat(li): add correlation insight

- package.json
> chore: remove useless devdep electron

- packages/lite-insight/src/insights/extractors/correlation.ts
- packages/lite-insight/src/pipeline/extract.ts
> fix(li): type fix

- packages/data-wizard/package.json
> chore(dw): move tslib from devDependencies to dependencies

- packages/lite-insight/__tests__/utils/aggr.test.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/utils/aggregate.ts
- add COUNT_DISTINCT aggregate function
- add tests for aggregate function
> feat(li): add COUNT_DISTINCT aggregate function

- packages/auto-chart/package.json
- packages/chart-advisor/README.md
- packages/chart-advisor/package.json
- packages/chart-advisor/zh-CN/README.zh-CN.md
- packages/ckb/package.json
- packages/data-wizard/package.json
- packages/lite-insight/package.json
- packages/smart-board/README.md
- packages/smart-board/package.json
- packages/smart-board/zh-CN/README.zh-CN.md
- sites/ava-site/docs/guide/auto-chart/intro.en.md
- sites/ava-site/docs/guide/auto-chart/intro.zh.md
- sites/ava-site/docs/guide/chart-advisor/intro.en.md
- sites/ava-site/docs/guide/chart-advisor/intro.zh.md
- sites/ava-site/docs/guide/smart-board/intro.en.md
- sites/ava-site/docs/guide/smart-board/intro.zh.md
- sites/ava-site/examples/chart-advisor/advise-and-lint/API.en.md
- sites/ava-site/examples/chart-advisor/advise-and-lint/API.zh.md
- sites/ava-site/examples/components/auto-chart/API.en.md
- sites/ava-site/examples/components/auto-chart/API.zh.md
- sites/ava-site/examples/smart-board/basic/API.en.md
- sites/ava-site/examples/smart-board/basic/API.zh.md
- sites/ava-site/package.json
Add repository info in `pakcage.json`, and modify AutoChart, ChartAdvisor, SmartBoard introduction file name to `intro`.
> chore: update package.json info

- package.json
> chore: update root package.json workspaces

- .github/workflows/auto-release.yml
- .github/workflows/release-notify.yml
- .github/workflows/sync-after-auto-release.yml
- .releaserc.js
- package.json
1. Add semantic-release to support auto release.
2. Add `auto-release.yml` workflow to run auto release and after stable brach updated.
3. Add `release-notification.yml` workflow to give the DingTalk group a notice after release.
4. Add `sync-packgejson-and-changelog-after-auto-release.yml` workflow to update master branch after auto release.
> chore: support auto release

- lerna.json
- packages/auto-chart/package.json
- packages/chart-advisor/package.json
- packages/ckb/package.json
- packages/data-wizard/package.json
- packages/lite-insight/package.json
- packages/smart-board/package.json
Update version with tag for 6 packages. Auto release will boot from 2.1.0.
> chore: update version with tag to boot auto release

- .github/workflows/sync-after-auto-release.yml
- lerna.json
> chore: add useWorkspaces for lerna

- packages/chart-advisor/__tests__/ckb.test.ts
- packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
> fix chart advisor tests and update jsdoc

- lerna.json
- package.json
Remove manual release script's no-private to update the package versions of the demo's deps.
Remove unnecessary `packages` config in `lerna.json`.
> chore: remove manual release script's no-private

- .github/workflows/auto-release.yml
- .github/workflows/sync-after-auto-release.yml
Add `npm install --no-package-lock` in Auto Release workflow to support `workspaces`.
Remove alpha test code in Sync After Auto Release workflow.
> chore: improve auto release related workflows

- .github/workflows/auto-release.yml
- .github/workflows/sync-after-auto-release.yml
- .releaserc.js
> chore: fix sync-after-auto-release workflow

- package.json
- packages/lite-insight/README.md
- packages/lite-insight/src/insight-browser/api.ts
- packages/lite-insight/src/insight-node/api.ts
- packages/lite-insight/zh-CN/README.zh-CN.md
- docs: add @deprecated annotation for async api
- chore: jest config
> docs(li): add @deprecated annotation for async api

- README.md
- zh-CN/README.zh-CN.md
> docs(readme): papers

- README.md
- packages/auto-chart/README.md
- packages/auto-chart/zh-CN/README.zh-CN.md
- packages/chart-advisor/README.md
- packages/chart-advisor/zh-CN/README.zh-CN.md
- packages/ckb/README.md
- packages/smart-board/README.md
- packages/smart-board/zh-CN/README.zh-CN.md
- sites/ava-site/docs/guide/auto-chart/intro.en.md
- sites/ava-site/docs/guide/auto-chart/intro.zh.md
- sites/ava-site/docs/guide/chart-advisor/intro.en.md
- sites/ava-site/docs/guide/chart-advisor/intro.zh.md
- sites/ava-site/docs/guide/smart-board/intro.en.md
- sites/ava-site/docs/guide/smart-board/intro.zh.md
- sites/ava-site/examples/chart-advisor/advise-and-lint/API.en.md
- sites/ava-site/examples/chart-advisor/advise-and-lint/API.zh.md
- sites/ava-site/examples/components/auto-chart/API.en.md
- sites/ava-site/examples/components/auto-chart/API.zh.md
- sites/ava-site/examples/smart-board/basic/API.en.md
- sites/ava-site/examples/smart-board/basic/API.zh.md
- zh-CN/README.zh-CN.md
Correct api link in Chinese README file.
> fix: correct api link in Chinese README file

- packages/chart-advisor/__tests__/rule.test.ts
- packages/chart-advisor/src/advisor/advice-pipeline/data-to-advices.ts
- packages/chart-advisor/src/advisor/utils/computeScore.ts
- packages/chart-advisor/src/advisor/utils/index.ts
- packages/chart-advisor/src/linter/index.ts
- packages/chart-advisor/src/linter/utils/getChartType.ts
- packages/chart-advisor/src/linter/utils/index.ts
- packages/chart-advisor/src/linter/utils/lintRules.ts
- packages/chart-advisor/src/ruler/interface.ts
- sites/ava-site/docs/api/chart-advisor/0_ChartAdvisor.en.md
- sites/ava-site/docs/api/chart-advisor/0_ChartAdvisor.zh.md
- sites/ava-site/docs/api/chart-advisor/10_Advisor.en.md
- sites/ava-site/docs/api/chart-advisor/10_Advisor.zh.md
- sites/ava-site/docs/api/chart-advisor/20_Linter.en.md
- sites/ava-site/docs/api/chart-advisor/20_Linter.zh.md
- sites/ava-site/docs/api/chart-advisor/30_Ruler.en.md
- sites/ava-site/docs/api/chart-advisor/30_Ruler.zh.md
Solve issue#464:
- add feature _customFeatures_ into interface _ChartRuleConfig_
- include _customFeatures_ in function _checkRules_ and _scoreRules_
> feat(chart-advisor): enabling customized interface Info

- packages/ava-react/zh-CN/README.zh-CN.md
Add readme file for ava-react.
> docs(ava-react): readme.md

- packages/ava/package.json
- packages/ava/src/index.ts
- packages/ava/src/ntv/generate/generateTextSpec.ts
- packages/ava/src/ntv/generate/index.ts
- packages/ava/src/ntv/generate/types.ts
- packages/ava/src/ntv/index.ts
- packages/ava/src/ntv/schema/common.ts
- packages/ava/src/ntv/schema/index.ts
- packages/ava/src/ntv/schema/paragraph.ts
- packages/ava/src/ntv/schema/phrase.ts
- packages/ava/src/ntv/schema/source.ts
- packages/ava/src/ntv/schema/structure.ts
- packages/ava/src/ntv/types.ts
- packages/ava/src/ntv/utils/index.ts
- packages/ava/src/ntv/utils/isSpecType.ts
- packages/ava/src/text/index.ts
- packages/ava/src/utils/arr2map.ts
- packages/ava/src/utils/index.ts
- packages/ava/src/utils/isType.ts
Migrate T8/packages/narrative-text-schema/src to ava/text, bilingual notes will commit by next pr.
The json schema file will collected into antv/ntv-schema repo, like [vega schema](https://github.com/vega/schema).
> feat(ava/ntv): text spec and related function

- packages/ava/src/__tests__/data/statistics/index.test.ts
- packages/ava/src/advisor/index.ts
- packages/ava/src/data/statistics/caches.ts
- packages/ava/src/data/statistics/index.ts
- packages/ava/src/data/utils/index.ts
- packages/ava/src/data/utils/isType/isDateString.ts
Add statistical methods used internally by ava.
In order to CR easily, I split commits into multiple PRs. This PR is merged on the premise that [feat(ava/data): add utils](https://github.com/antvis/AVA/pull/479) is merged.
> refactor(ava/data): migrate and improve statistics

- packages/ava/__tests__/data/dataAnalysis/field/index.test.ts
- packages/ava/__tests__/data/statistics/index.test.ts
- packages/ava/__tests__/data/utils/common.test.ts
- packages/ava/__tests__/data/utils/isType/isDateString.test.ts
- packages/ava/__tests__/data/utils/isType/isType.test.ts
- packages/ava/src/data/dataAnalysis/field/index.ts
- packages/ava/src/data/dataAnalysis/field/types.ts
- packages/ava/src/data/dataAnalysis/graph/index.ts
- packages/ava/src/data/dataAnalysis/graph/types.ts
- packages/ava/src/data/dataAnalysis/index.ts
- packages/ava/src/data/dataAnalyze/index.ts
- packages/ava/src/data/index.ts
- packages/ava/src/data/statistics/index.ts
- packages/ava/src/data/types.ts
- packages/ava/src/index.ts
- packages/ava/tsconfig.json
- packages/data-wizard/src/analyzer/index.ts
Migrate and improve dataAnalysis, and add tests for it.
> refactor(ava/data): migrate and improve dataAnalysis

- packages/ava/src/ckb/base.ts
- packages/ava/src/ckb/i18n/zh-CN.ts
- packages/ava/src/data/statistics/index.ts
- packages/ava/src/data/utils/isType/index.ts
> fix: issues while build

- packages/ava/package.json
- packages/ava/src/data/analysis/graph/index.ts
- packages/ava/tsconfig.json
> Fix build path and graph dep issue

- packages/ava/src/insight/algorithms/change-point/buishand-u.ts
- packages/ava/src/insight/insights/extractors/correlation.ts
> fix(ava/insight): fix build error

- package.json
- rollup.config.js
> chore: fix build error

- packages/ava/src/advisor/index.ts
- packages/ava/src/advisor/types.ts
- packages/ava/src/index.ts
Fix index and advisor exports.
> fix(ava): fix exports

- playground/src/DevPlayground/Data/index.tsx
- playground/src/DevPlayground/LiteInsight/AutoInsight.tsx
- playground/src/DevPlayground/LiteInsight/index.tsx
- playground/src/manifest.tsx
- playground/src/pages/index.tsx
> docs(playground): update Data and Insight with new API

- packages/ava/__tests__/advisor/rule.test.ts
- packages/ava/__tests__/data/dataset/field/dataFrame/getValueFunctions.test.ts
- packages/ava/src/advisor/advise-pipeline/advicesForChart.ts
- packages/ava/src/advisor/advise-pipeline/data-to-advices.ts
- packages/ava/src/advisor/advise-pipeline/spec-mapping.ts
- packages/ava/src/advisor/lint-pipeline/check-rules.ts
- packages/ava/src/advisor/ruler/rules/limit-series.ts
- packages/ava/src/advisor/utils/deep-mix.ts
- packages/ava/src/advisor/utils/index.ts
- packages/ava/src/ckb/base.ts
- packages/ava/src/ckb/ckb.ts
- packages/ava/src/ckb/constants.ts
- packages/ava/src/ckb/i18n/index.ts
- packages/ava/src/ckb/i18n/types.ts
- packages/ava/src/ckb/i18n/zh-CN.ts
- packages/ava/src/ckb/index.ts
- packages/ava/src/ckb/types.ts
- packages/ava/src/data/dataset/field/baseFrame.ts
- packages/ava/src/data/dataset/field/dataFrame.ts
- packages/ava/src/data/dataset/field/series.ts
- packages/ava/src/insight/pipeline/extract.ts
- packages/ava/src/insight/visualization/index.ts
> docs(ava): remove redundant comments and assign 3.0.0 todo to developers

- packages/ava-react/src/NarrativeTextVis/index.ts
> fix(ava-react/ntv): rename export variable names

- packages/ava-react/README.md
- packages/ava-react/package.json
- packages/ava/README.md
> chore: update ava and ava-react README

- package.json
- packages/ava-react/package.json
> chore: add antd to ava-react devDep and modify AVA workspaces

- packages/ava-react/.fatherrc.ts
- packages/ava-react/package.json
- packages/ava-react/rollup.config.js
- playground/src/DevPlayground/NTV/index.tsx
- playground/src/manifest.tsx
> chore: build ava-react by father

- README.md
- README.zh-CN.md
> docs: fix readme v3 img url

- package.json
- site/.dumirc.ts
- site/package.json
> docs(site): upgrade theme and site info

- packages/ava/__tests__/advisor/dataprops.test.ts
- packages/ava/src/advisor/advise-pipeline/advicesForChart.ts
- packages/ava/src/advisor/types.ts
- site/.dumirc.ts
In this way, user can assgin specific dataProps to specific field. 
For example, user can assign levelOfMeasurements of some fields using their own knoweledge instead of using dataFrame.
> feat(ava/advisor): user can input partial dataProps

- packages/ava/package.json
- packages/ava/src/insight/algorithms/change-point/index.ts
- packages/ava/src/insight/insights/index.ts
> solve package size issue temporarily & update version to 3.0.0-alpha.3

- demo/package.json
- packages/lite-insight/package.json
- packages/smart-board/package.json
> chore: upgrade lite-insight version

- packages/ava/package.json
> chore(ava): fix dist entry and update version to 3.0.0-alpha.4

- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createCompare.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createOtherMetricValue.tsx
- packages/ava-react/src/NarrativeTextVis/styled/entity.tsx
- site/docs/api/ntv/intro.zh.md
- site/docs/guide/ntv/intro.zh.md
- site/docs/guide/ntv/plugin.en.md
- site/docs/guide/ntv/plugin.zh.md
- site/examples/ntv/custom/demo/block.tsx
- site/examples/ntv/custom/demo/entity.tsx
- site/examples/ntv/custom/demo/meta.json
- site/examples/ntv/interactive/demo/analysis.tsx
> docs(ava-react/ntv): add ntv plugins docs

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/theme/seed.ts
> fix(ava-react/ntv): dark base color

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/NarrativeTextVis.tsx
- packages/ava-react/src/NarrativeTextVis/index.ts
- packages/ava-react/src/NarrativeTextVis/paragraph/Bullets.tsx
- packages/ava-react/src/NarrativeTextVis/paragraph/Heading.tsx
- packages/ava-react/src/NarrativeTextVis/paragraph/Headline.tsx
- packages/ava-react/src/NarrativeTextVis/paragraph/TextLine.tsx
- packages/ava-react/src/NarrativeTextVis/phrases/index.tsx
- packages/ava-react/src/NarrativeTextVis/section/index.tsx
- packages/ava-react/src/NarrativeTextVis/styled/bullet.tsx
- packages/ava-react/src/NarrativeTextVis/types/props.ts
- packages/ava-react/src/NarrativeTextVis/utils/getCollapseProps.tsx
- packages/ava-react/src/NarrativeTextVis/utils/index.ts
- playground/.umirc.ts
- playground/src/DevPlayground/NTV/index.tsx
- playground/src/pages/index.tsx
- site/docs/api/ntv/intro.en.md
- site/docs/api/ntv/intro.zh.md
- site/examples/ntv/basic/demo/collapse.tsx
- site/examples/ntv/basic/demo/meta.json
> feat(ava-react/ntv): support bullets collapse and expand

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/styled/entity.tsx
- site/docs/guide/ntv/ntv-schema.zh.md
- site/package.json
> fix(ava-react/ntv): entity as inline element

- packages/chart-advisor/src/ruler/rules/index.ts
- packages/ckb/package.json
- packages/ckb/src/chartID.ts
- packages/ckb/src/interface.ts
- packages/lite-insight/src/interface.ts
- packages/lite-insight/src/narrative/interface.ts
> chore(ava/ckb): mv node dep to dev deps

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/styled/entity.tsx
> fix(ava-react/ntv): break word when word overflow

- site/.dumirc.ts
- site/docs/guide/intro.en.md
- site/docs/guide/intro.zh.md
> Bm site update

- packages/chart-advisor/src/advisor/index.ts
> feat(chart-advisor): support define fieldTypes when call advicesForChart

- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
- site/examples/insight/basic/API.en.md
- site/examples/insight/basic/API.zh.md
- site/examples/insight/custom/API.en.md
- site/examples/insight/custom/API.zh.md
- site/examples/insight/visualization/API.en.md
- site/examples/insight/visualization/API.zh.md
> docs(site): update usage of insight

- package.json
- packages/ava/__tests__/unit/advisor/advise-pipeline/infer-data-type.test.ts
- packages/ava/__tests__/unit/advisor/advise-pipeline/spec.test.ts
- packages/ava/__tests__/unit/advisor/index.test.ts
- packages/ava/__tests__/unit/advisor/ruler/rule.test.ts
- packages/ava/package.json
- packages/ava/src/advisor/advise-pipeline/data-to-advices.ts
- packages/ava/src/advisor/advise-pipeline/spec-mapping.ts
- packages/ava/src/advisor/lint-pipeline/check-rules.ts
- packages/ava/src/advisor/lint-pipeline/getChartType.ts
- packages/ava/src/advisor/lint-pipeline/lintRules.ts
- packages/ava/src/advisor/ruler/rules/bar-without-axis-min.ts
- packages/ava/src/advisor/ruler/rules/x-axis-line-fading.ts
- packages/ava/src/advisor/types.ts
- packages/ava/src/advisor/utils/inferDataType.ts
- packages/ava/src/common/types.ts
- playground/package.json
- playground/src/DevPlayground/ChartAdvisor/Chart.tsx
1. modify spec-mapping based on g2-spec
2. add g2-spec type definition and the function of inferring data type
3. update lint rules with optimizer
4. update advisor and ruler's tests
> feat: update Advisor with g2-spec

- packages/ava/src/insight/narrative/utils/phrases-builder.ts
- packages/ava/src/insight/pipeline/index.ts
- packages/ava/src/insight/pipeline/insight.ts
- packages/ava/src/insight/types.ts
- packages/ava/src/insight/visualization/index.ts
- playground/src/DevPlayground/LiteInsight/AutoInsight.tsx
- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/examples/ntv/case/demo/chart-explanation.tsx
> fix(ava/insight): change 'schema' to 'spec' in api

- site/.dumirc.ts
- site/docs/guide/migrate/tov2fromv1.en.md
- site/docs/guide/migrate/tov2fromv1.zh.md
- site/docs/guide/migrate/tov3fromv2.en.md
- site/docs/guide/migrate/tov3fromv2.zh.md
> docs(site): reorg migrate doc and add v2 to v3 migrate

- packages/ava/__tests__/integration/advisor/dataprops.test.ts
- packages/ava/__tests__/unit/advisor/utils/utils.test.ts
- packages/ava/src/advisor/advise-pipeline/data-to-advices.ts
- packages/ava/src/advisor/types.ts
- playground/package.json
- playground/src/DevPlayground/ChartAdvisor/Linter/LinterPanel.tsx
- playground/src/DevPlayground/NTV/index.tsx
1. modify integration test based on g2-spec
2. update playground's linterPanel with g2-spec
> feat: modify integration test based on g2-spec

- packages/ava/__tests__/integration/advisor/dataprops.test.ts
- packages/ava/__tests__/unit/advisor/advise-pipeline/spec.test.ts
- packages/ava/__tests__/unit/advisor/index.test.ts
- packages/ava/src/advisor/advise-pipeline/spec-mapping.ts
- packages/ava/src/advisor/ruler/rules/x-axis-line-fading.ts
- playground/src/DevPlayground/ChartAdvisor/Linter/LinterPanel.tsx
- site/examples/advice/advise-and-lint/demo/custom-ckb-ca.jsx
- site/examples/advice/advise-and-lint/demo/custom-ckb-rules-ca.jsx
- site/examples/advice/advisor-only/demo/custom-ckb-advisor.jsx
- site/examples/advice/linter-only/demo/chart-linter.jsx
- site/examples/advice/linter-only/demo/custom-rules-linter.jsx
- site/examples/advice/linter-only/demo/fixer.jsx
- site/examples/advice/linter-only/demo/linter-steps.jsx
> feat: format demo spec as g2-spec

- packages/ava/src/data/statistics/IQR.ts
- packages/ava/src/data/statistics/cdf.ts
- packages/ava/src/insight/constant.ts
- packages/ava/src/insight/insights/extractors/categoryOutlier.ts
- packages/ava/src/insight/insights/extractors/changePoint.ts
- packages/ava/src/insight/insights/extractors/timeSeriesOutlier.ts
- packages/ava/src/insight/pipeline/extract.ts
- packages/ava/src/insight/pipeline/insight.ts
- packages/ava/src/insight/pipeline/preprocess.ts
- packages/ava/src/insight/types.ts
- packages/ava/src/insight/utils/aggregate.ts
- packages/ava/src/insight/visualization/index.ts
- playground/package.json
- playground/src/DevPlayground/LiteInsight/AutoInsight.tsx
> feat(ava/insight): improve timeSeriesOutlier pattern to generate more information

- site/examples/others/thumbnails/demo/select.jsx
> fix(site): fix thumbnails select demo with new antd menu

- packages/ava/__tests__/unit/data/statistics/index.test.ts
> test(ava/data): add test cases of cdf

- packages/ava/__tests__/unit/advisor/advise-pipeline/spec.test.ts
- packages/ava/src/advisor/advise-pipeline/spec-mapping.ts
> refactor: modify bar's mapping & docs: add spec-mapping function test

- packages/ava/__tests__/integration/insight/insight.test.ts
> test(ava/insight): add test cases for various types of info

- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
> docs(site): update images of insight and fix style issues

- packages/ava/__tests__/unit/advisor/ruler/rule-cases/bar-series-qty.test.ts
- packages/ava/__tests__/unit/advisor/ruler/rule-cases/bar-without-axis-min.test.ts
- packages/ava/src/advisor/advise-pipeline/spec-mapping.ts
增加对 lint rule 本身的 test，包含 type、 trigger、validator（chartRule）、optimizer（designRule）
> test: add lint rules' test cases demo

- packages/ava/__tests__/integration/insight/insight.test.ts
- packages/ava/__tests__/unit/insight/algorithms/IQR.test.ts
- packages/ava/__tests__/unit/insight/algorithms/mannkendall-test.test.ts
- packages/ava/__tests__/unit/insight/algorithms/pettitt-test.test.ts
- packages/ava/__tests__/unit/insight/extractors/category-outlier.test.ts
- packages/ava/__tests__/unit/insight/extractors/change-point.test.ts
- packages/ava/__tests__/unit/insight/extractors/correlation.test.ts
- packages/ava/__tests__/unit/insight/extractors/low-variance.test.ts
- packages/ava/__tests__/unit/insight/extractors/majority.test.ts
- packages/ava/__tests__/unit/insight/extractors/time-series-outlier.test.ts
- packages/ava/__tests__/unit/insight/extractors/trend.test.ts
- packages/ava/__tests__/unit/insight/utils/aggr.test.ts
fix insight test error due to insight api changes
dimension: string -> dimension: {fieldName: string}
measure: {field: string } -> measure: {fieldName: string}
> test(ava/insight): fix insight test error due to api adjust

- packages/ava/src/insight/chart/strategy/augmentedMarks/timeSeriesOutlier.ts
- packages/ava/src/insight/chart/strategy/chart.ts
- packages/ava/src/insight/chart/strategy/commonMarks/areaMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/lineMark.ts
- packages/ava/src/insight/chart/types.ts
- playground/src/DevPlayground/LiteInsight/AutoInsight.tsx
- site/examples/insight/visualization/demo/index.jsx
- site/examples/insight/visualization/demo/meta.json
> fix(ava/insight): adjust timeSeriesOutlier marks order

- packages/ava/__tests__/integration/insight/insight.test.ts
> test(ava/insight): fix test error due to api update

- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
- site/docs/guide/migrate/tov3fromv2.en.md
- site/docs/guide/migrate/tov3fromv2.zh.md
> docs(site): update insight api & v3 guide

- packages/ava-react/common/styles/index.less
- packages/ava-react/package.json
- packages/ava-react/src/InsightCard/InsightCard.tsx
- packages/ava-react/src/InsightCard/Title/index.less
- packages/ava-react/src/InsightCard/Title/index.tsx
- packages/ava-react/src/InsightCard/Toolbar/constants.ts
- packages/ava-react/src/InsightCard/Toolbar/defaultTools.tsx
- packages/ava-react/src/InsightCard/Toolbar/index.less
- packages/ava-react/src/InsightCard/Toolbar/index.tsx
- packages/ava-react/src/InsightCard/Toolbar/types.ts
- packages/ava-react/src/InsightCard/constants.tsx
- packages/ava-react/src/InsightCard/index.less
- packages/ava-react/src/InsightCard/index.ts
- packages/ava-react/src/InsightCard/ntvPlugins/components/ChartCarousel.tsx
- packages/ava-react/src/InsightCard/ntvPlugins/components/G2Chart.tsx
- packages/ava-react/src/InsightCard/ntvPlugins/index.ts
- packages/ava-react/src/InsightCard/ntvPlugins/plugins/chartPlugin.tsx
- packages/ava-react/src/InsightCard/ntvPlugins/types.ts
- packages/ava-react/src/InsightCard/types.ts
- packages/ava-react/src/InsightCard/utils/specGenerator.ts
- packages/ava-react/src/index.ts
- packages/ava/package.json
- packages/ava/src/insight/chart/strategy/augmentedMarks/categoryOutlier.ts
- playground/package.json
- playground/src/DevPlayground/LiteInsight/AutoInsight.tsx
- playground/src/DevPlayground/LiteInsight/mockSpec.ts
Add InsightCard component to support visualize and find data insights
> feat(ava-react/insight-card): add InsightCard component 

- packages/ava-react/package.json
- packages/ava/package.json
> chore(release): update version to v3 beta

- site/examples/insight/custom/demo/homogeneous.jsx
- site/examples/insight/custom/demo/impact.jsx
- site/examples/ntv/case/demo/chart-explanation.tsx
- site/package.json
> docs(ava): upgrade insight site demo

- README.md
- README.zh-CN.md
- site/.dumirc.ts
- site/docs/guide/intro.en.md
- site/docs/guide/intro.zh.md
> docs: update v3 framework image

- packages/ava/src/advisor/advise-pipeline/data-to-advices.ts
- site/examples/advice/smart-color/demo/auto-color.jsx
- site/examples/advice/smart-color/demo/data-advisor.jsx
> docs(site/smart-color): fix demo error in smart color

- site/examples/insight/custom/demo/homogeneous.jsx
- site/examples/insight/custom/demo/impact.jsx
- site/examples/insight/custom/demo/insight-type.jsx
- site/examples/insight/visualization/demo/index.jsx
> docs(site): replace ChartView with InsightCard

- packages/ava/src/insight/chart/strategy/augmentedMarks/timeSeriesOutlier.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/trend.ts
- packages/ava/src/insight/chart/strategy/commonMarks/areaMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/intervalMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/lineMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/pointMark.ts
- packages/ava/src/insight/chart/types.ts
> fix(ava/insight): modify array encode to object encode

- packages/ava/__tests__/integration/advisor/advise-cases/charts/pie.test.ts
- packages/ava/__tests__/unit/advisor/ruler/rule-cases/diff-pie-sector.test.ts
> test: fix diff-pie-sector and pie tests

- packages/ava-react/package.json
- packages/ava/package.json
- playground/package.json
- site/package.json
> chore(release): update version to 3.0.0

- packages/ava-react/src/InsightCard/utils/specGenerator.ts
> fix(ava-react/insight-card): fix import ava path

- packages/ava-react/package.json
> chore(ava-react): update version to 3.0.1

- site/.dumi/global.ts
- site/package.json
> chore(site): update gh-pages deploy script

- site/examples/advice/advise-and-lint/demo/meta.json
- site/examples/advice/advisor-only/demo/meta.json
- site/examples/advice/advisor-only/index.zh.md
- site/examples/advice/linter-only/demo/meta.json
- site/examples/advice/linter-only/index.en.md
- site/examples/advice/linter-only/index.zh.md
> docs(site/advisor): revise class advisor and linter as functions

- packages/ava-react/package.json
- packages/ava/package.json
- packages/ava/src/insight/chart/generator/insights.ts
- packages/ava/src/insight/chart/strategy/chart.ts
- packages/ava/src/insight/chart/strategy/viewSpec.ts
- packages/ava/src/utils/dataFormat.ts
- fix: correlation chart and coefficient
> fix(insight): fix spec generator for correlation and majority

- packages/ava/src/advisor/types.ts
- packages/ava/src/index.ts
> chore(ava/advisor): export type RuleModule

- site/docs/guide/ntv/ntv-schema.zh.md
> docs(site): update ntv-schema url

- packages/ava/src/index.ts
> fix(ava/advisor): export AdvisorConfig type

- packages/ava-react/src/NarrativeTextVis/phrases/Phrase.tsx
- packages/ava/src/index.ts
- packages/ava/src/ntv/schema/phrase.ts
- packages/ava/src/ntv/types.ts
- packages/ava/src/ntv/utils/isSpecType.ts
- playground/src/DevPlayground/NTV/index.tsx
- site/docs/guide/intro.en.md
- site/docs/guide/intro.zh.md
- site/docs/guide/ntv/intro.zh.md
- site/docs/guide/ntv/ntv-comp.zh.md
- site/docs/guide/ntv/ntv-schema.zh.md
ATT
```js
const spec = {
sections: [
{
paragraphs: [
{
type: 'normal',
phrases: [
{
type: 'text',
value: '在 text 中的转义字符字符 \r\n 无效，后面是 escape 类型短语，换行：',
},
{
type: 'escape',
value: '\n',
},
{
type: 'text',
value: '回车',
},
{
type: 'escape',
value: '\r',
},
],
},
],
},
],
}
```
> feat(ava/ntv): add escape phrase

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/phrases/Phrase.tsx
- packages/ava-react/src/NarrativeTextVis/styled/index.tsx
- packages/ava-react/src/NarrativeTextVis/styled/phrase.tsx
- packages/ava/src/index.ts
- packages/ava/src/ntv/schema/phrase.ts
- packages/ava/src/ntv/types.ts
- packages/ava/src/ntv/utils/isSpecType.ts
- playground/package.json
- playground/src/DevPlayground/NTV/index.tsx
- playground/src/global.css
```jsx
<NarrativeTextVis
spec={{
sections: [
{
paragraphs: [
{
type: 'normal',
phrases: [
{
type: 'text',
value: '渲染公式：',
},
{
type: 'formula',
// eslint-disable-next-line no-useless-escape, quotes
value: `c = \\pm\\sqrt{a^2 + b^2}`,
},
],
},
],
},
],
}}
/>
```
> feat(ava/ntv): add formula phrase

- site/.dumirc.ts
> docs(site): hide internal site

- packages/ava/__tests__/unit/advisor/ruler/rule-cases/data-check.test.ts
- packages/ava/src/advisor/ruler/rules/data-check.ts
- site/package.json
#678 
原本的规则，只检查了 ckb 中要求的字段能不能被填满；但是没有检查，数据中的字段有没有被全部使用上。因此会导致推荐出错。
> Fix data check rule

- packages/ava-react/package.json
> chore(ava-react): update version to release

- commitlint.config.js
> chore(global): update commit lint rules

- packages/ava/src/data/analysis/field/index.ts
- packages/ava/src/data/dataset/field/baseFrame.ts
- packages/ava/src/data/dataset/field/dataFrame.ts
- packages/ava/src/data/dataset/field/types.ts
- packages/ava/src/data/utils/isType/isDateString.ts
- packages/ava/src/insight/pipeline/insight.ts
- packages/ava/src/insight/pipeline/preprocess.ts
- packages/ava/src/insight/types.ts
- site/examples/data/data-frame/demo/info.jsx
> fix(ava): method for identifying date format

- README.zh-CN.md
1. Optimize and restructure the structure (9 parts): intro, composition, features, documentations, usage methods, contribution, collaborating institutions, academic achievements, and license.
2. Replace the original AVA architecture image with a chart example pic : 
<div align="center"><img width="800" src="https://mdn.alipayobjects.com/huamei_kjfwsg/afts/img/A*wpo3RpdULnAAAAAAAAAAAAAADvmcAQ/original" alt="AVA intro">
</div>
3. According to the suggestions, the markdown syntax errors were corrected, the case was optimized, the 'development' section was deleted, and the description and usage of the AVA components were optimized.
> docs(global): Optimize and improve the readme.zh-CN.md.

- packages/ava-react/src/InsightCard/InsightCard.tsx
- packages/ava-react/src/InsightCard/Title/index.tsx
- packages/ava-react/src/InsightCard/constants.tsx
- packages/ava-react/src/InsightCard/ntvPlugins/index.ts
- packages/ava-react/src/InsightCard/ntvPlugins/plugins/subspaceDescriptionPlugin.tsx
- packages/ava-react/src/InsightCard/utils/specGenerator.ts
- packages/ava/src/insight/narrative/strategy/timeSeriesOutlier.ts
> fix(insight): fix display of insight subspace & time series outlier description

- packages/ava-react/package.json
- packages/ava/package.json
> chore(global): update version to release

- README.md
1.  Translate Chinese documents into English.
2. Change the Chinese in the 2 pictures to English.
<div align="center">
</div>
<div align="center">
</div>
> docs(global): revise the English document based on the revised Chinese document

- README.md
- README.zh-CN.md
- [0] fixed #0
- [0] add / modify test cases
- [2] documents, demos
> docs(global): optimize English and Chinese readme documents

- site/.dumi/global.ts
- site/docs/guide/ntv/ntv-schema.zh.md
- site/examples/ntv/basic/demo/extra-phrases.tsx
- site/examples/ntv/basic/demo/meta.json
- site/package.json
resolve https://github.com/antvis/AVA/issues/653
- 增加短语类型描述；
- 更新 ntv-schema 配图；
> docs(ava/ntv): add ntv-schema phrase type description & demo

- packages/ava/zh-CN/README.zh-CN.md
add definitions, add use cases
> docs(ava): improve ava readme.zh-CN 

- packages/ava/__tests__/integration/insight/insight.test.ts
- packages/ava/src/insight/insights/checkers.ts
- packages/ava/src/insight/insights/extractors/lowVariance.ts
> fix(ava/insight): fix low variance method

- packages/ava/README.md
1. modify the npm link error in the en documentation.
2. add intro section.
3. optimize cases.
4. synchronize the contribution section with the global document.
> docs(ava): optimize and improve ava readme-en

- CONTRIBUTING.md
- CONTRIBUTING.zh-CN.md
1. Adjust the language style to make it more formal. The core content is basically unchanged.
2. Adjust the content structure and image placement of **submit issues**.
> docs(global):  improve  contributing.md and contributing.zh-CN.md more official

- packages/ava-react/README.md
- packages/ava-react/zh-CN/README.zh-CN.md
add introduction and examples.
> docs(ava-react):improve readme of ava-react.zh and ava-react.en 

- packages/ava/__tests__/integration/insight/insight.test.ts
- packages/ava/__tests__/unit/insight/extractors/category-outlier.test.ts
- packages/ava/__tests__/unit/insight/extractors/change-point.test.ts
- packages/ava/__tests__/unit/insight/extractors/correlation.test.ts
- packages/ava/__tests__/unit/insight/extractors/low-variance.test.ts
- packages/ava/__tests__/unit/insight/extractors/majority.test.ts
- packages/ava/__tests__/unit/insight/extractors/time-series-outlier.test.ts
- packages/ava/__tests__/unit/insight/extractors/trend.test.ts
- packages/ava/src/insight/insights/extractors/categoryOutlier.ts
- packages/ava/src/insight/insights/extractors/changePoint.ts
- packages/ava/src/insight/insights/extractors/correlation.ts
- packages/ava/src/insight/insights/extractors/lowVariance.ts
- packages/ava/src/insight/insights/extractors/majority.ts
- packages/ava/src/insight/insights/extractors/timeSeriesOutlier.ts
- packages/ava/src/insight/insights/extractors/trend.ts
- packages/ava/src/insight/insights/util.ts
- packages/ava/src/insight/pipeline/extract.ts
- packages/ava/src/insight/types.ts
before
after
use IQR method
use normality test
> feat(ava/insight): allows users to adjust the detection method of outliers

- packages/ava/src/data/analysis/field/index.ts
> fix(ava/data): method to get the recommendation field type

- packages/ava/__tests__/unit/ntv/generate.test.ts
- packages/ava/src/ntv/generate/generateTextSpec.ts
- packages/ava/src/ntv/schema/phrase.ts
> feat(ava/ntv): metadata carrying variable information when generating text spec

- packages/ava-react/src/NarrativeTextVis/paragraph/TextLine.tsx
- packages/ava-react/src/NarrativeTextVis/styled/paragraph.tsx
- packages/ava/src/ntv/schema/paragraph.ts
- site/docs/guide/ntv/ntv-schema.zh.md
- site/examples/ntv/basic/demo/meta.json
- site/examples/ntv/basic/demo/paragraph.tsx
https://github.com/antvis/AVA/issues/673
> feat(ava,ava-react): ntv paragraph support indents

- packages/ava-react/package.json
- packages/ava/package.json
> chore release  ava 3.0.6 & ava-react 3.1.6

- packages/ava-react/src/NarrativeTextVis/phrases/Phrase.tsx
> fix(ava-react/ntv): fix styles not working in text phrase

- packages/ava/package.json
- packages/ava/src/insight/index.ts
> feat(ava/insight): add insight extractor api & release version 3.2.0

- packages/ava/package.json
- packages/ava/src/index.ts
export insightPatternsExtractor method and props
> feat(ava/insight): release insight extractor method and props

- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createCompare.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createContributeRatio.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createMetricValue.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createOtherMetricValue.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/presets/createProportion.tsx
- packages/ava-react/src/utils/index.ts
- packages/ava-react/src/utils/isType.ts
- packages/ava/src/ntv/generate/generateTextSpec.ts
- packages/ava/src/ntv/generate/utils.ts
- packages/ava/src/utils/isType.ts
> fix: ntv can handle number string

- packages/ava-react/package.json
- packages/ava/package.json
> chore: release ava 3.2.0 & ava-react 3.2.1

- packages/ava/src/index.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/changePoint.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/index.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/timeSeriesOutlier.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/trend.ts
- packages/ava/src/insight/chart/types.ts
- packages/ava/src/insight/pipeline/specificInsight.ts
- packages/ava/src/insight/types.ts
transform augmentedMarksStrategy to generate customized augmented marks
> fix(ava/insight): modify the structure of insight mark

- packages/ava/src/insight/chart/generator/insights.ts
> fix(ava/insight): delete generateInsightAugmentedMarks method

- packages/ava/src/index.ts
- packages/ava/src/insight/chart/index.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/categoryOutlier.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/changePoint.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/lowVariance.ts
- packages/ava/src/insight/chart/types.ts
- packages/ava/src/insight/chart/utils.ts
- packages/ava/src/insight/index.ts
- packages/ava/src/insight/pipeline/specificInsight.ts
- packages/ava/src/insight/types.ts
> feat(ava/insight): add LowVarianceMark and CategoryOutlierMark

- packages/ava-react/src/NarrativeTextVis/paragraph/index.tsx
- packages/ava/src/index.ts
- packages/ava/src/ntv/schema/paragraph.ts
- packages/ava/src/ntv/utils/isSpecType.ts
- site/docs/guide/ntv/ntv-schema.zh.md
> feat(ava,ava-react/ntv): support divider paragraph

- site/.dumirc.ts
- site/package.json
> chore(global): update dumi-theme-antv style

- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/docs/api/insight/get-specific-insight.en.md
- site/docs/api/insight/get-specific-insight.zh.md
- site/docs/api/insight/insight-patterns-extractor.en.md
- site/docs/api/insight/insight-patterns-extractor.zh.md
- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
- site/examples/insight/basic/demo/meta.json
- site/examples/insight/basic/demo/specify-type.jsx
> docs(ava/insight): add guidance and demo for insightPatternsExtractor and getSpecificInsight

- packages/ava/src/data/statistics/bayesian.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/changePoint.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/lowVariance.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/timeSeriesOutlier.ts
- packages/ava/src/insight/chart/strategy/augmentedMarks/trend.ts
- packages/ava/src/insight/chart/strategy/chart.ts
- packages/ava/src/insight/chart/strategy/commonMarks/areaMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/intervalMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/lineMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/pointMark.ts
- packages/ava/src/insight/chart/strategy/commonMarks/textMark.ts
- packages/ava/src/insight/insights/extractors/changePoint.ts
- packages/ava/src/insight/insights/index.ts
- packages/ava/src/insight/insights/util.ts
- packages/ava/src/insight/pipeline/specificInsight.ts
给BayesianChangePoint方法补充chunkSize和iteratee
> fix(ava/insight): solve the problem of BayesianChangePoint method under large data volume & optimize  getSpecificInsight method

- packages/ava/src/advisor/ruler/rules/index.ts
- site/.dumirc.ts
- site/docs/api/advice/Ruler.en.md
- site/docs/api/advice/Ruler.zh.md
- site/docs/guide/advice/rules.en.md
- site/docs/guide/advice/rules.zh.md
1.fix rule id
2.add documents of rule set
> fix(ava/advisor): fix rule id & add explanation for rules used in advisor module

- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
> docs(ava/insight): update the links in guide

- packages/ava-react/src/NarrativeTextVis/phrases/Phrase.tsx
- packages/ava/src/index.ts
- packages/ava/src/ntv/schema/phrase.ts
- packages/ava/src/ntv/utils/isSpecType.ts
- site/docs/guide/ntv/ntv-schema.zh.md
> feat(ava,ava-react/ntv): add image phrase

- site/docs/api/insight/auto-insights.en.md
- site/docs/api/insight/auto-insights.zh.md
- site/docs/guide/insight/intro.en.md
- site/docs/guide/insight/intro.zh.md
1.  Provide a table about optional extractors for setting insightTypes in api/insight
2. Provide a guidance about setting custom insight types in guide/insight
3. provide a guide about setting impactMeasures and impactWeight.
> docs(ava/insight): provide a brief instruction about Insight extractors

- packages/ava-react/package.json
- packages/ava/package.json
> chore(ava,ava-react): release ava v3.4.0 and ava-react v3.3.0

- packages/ava-react/package.json
- packages/ava-react/src/NarrativeTextVis/NarrativeTextVis.tsx
- packages/ava-react/src/NarrativeTextVis/chore/plugin/plugin-protocol.type.ts
- packages/ava-react/src/NarrativeTextVis/types/props.ts
See commit message for details
> fix(ava-react/ntv): hotfix ntv copy and plugin type function
