packages/chart-advisor/src/auto-chart.ts
重复调用 autoChart 时，destroy noDataLayer 后未初始化，导致再次调用 destroy 失败。
=> fix(chart-advisor): uninitialize noDataLayer

common/reviews/api/chart-advisor.api.md, packages/chart-advisor/__tests__/unit/pipeline/data-to-specs.test.ts, packages/chart-advisor/__tests__/unit/pipeline/dataprops-to-advices.test.ts, packages/chart-advisor/src/advice-pipeline/dataprops-to-advices.ts, packages/chart-advisor/src/advice-pipeline/interface.ts, packages/chart-advisor/src/advice-pipeline/spec-mapping.ts
新增 chartType 为 table 时的 spec，目前包括配置项有
* rows 行头
* columns 列头
* values 值字段
=> feat: add table advice spec

package.json, packages/chart-advisor/package.json, packages/datawizard/analyzer/package.json, packages/datawizard/analyzer/src/index.ts, packages/datawizard/random/package.json, packages/datawizard/transform/package.json, packages/knowledge/package.json
不是数据量大的问题，特定数据里面推断出来有可能的 types: string integer date，结果获得 date 子集的时候把 integer 也包含进去了，就无限循环了。
=> fix(datawizard-analyzer): maximum call stack size

common/reviews/api/dw-transform.api.md, packages/datawizard/transform/src/reshape/stack.ts, packages/knowledge/src/base.ts
=> Remove comparison purpose of stacked area chart

demo/AutoChartTest.tsx, packages/chart-advisor/__tests__/bugs/config-panel-disappear.test.ts, packages/chart-advisor/__tests__/bugs/issue-116.test.ts, packages/chart-advisor/__tests__/utils/dom.ts, packages/chart-advisor/__tests__/utils/wait.ts, packages/chart-advisor/src/auto-chart/auto-chart.ts, packages/chart-advisor/src/auto-chart/config-panel.ts, packages/chart-advisor/src/i18n/index.ts
- fix: config panel disappear and add a test case
- fix: panel language use option rather than `getLanguage`
=> fix(chart-advisor): config panel disappear

packages/datawizard/random/__tests__/text-random.test.ts, packages/datawizard/random/src/text-random.ts
1. fix the wrong length of mobile numbers when asterisks added
2. the first three digits can be specified, otherwise the param is invalid
=> fix: the first three digits of phone numbers can be specified

demo/package.json, demo/webpack.config.js
When we start demo, we will find some errors like `Module not found: Error: Can't resolve '@babel/runtime/helpers/typeof' in 'AVA/packages/data-wizard/esm/analyzer'`.
The reason is lerna's symlink npm package is considered as relative path instead of `node_modules` by babel. Packages' files will be resolved by babel. And node will find `@babel/runtime` from inner to outer. There is no `@babel/runtime` in `data-wizard`, and no `@babel/runtime` in root. It only exists in `demo`.
There was no such issue in v1 because we put `webpack.config.js` and related packages in root.
So........ We can solve the issue in the following two ways:
- Move @babel/runtime devDep from demo to root.
- Remove `@babel/plugin-transform-runtime` and `@babel/runtime`. In fact, we don't have to support ES5 in demo. …
=> chore: fix @babel/runtime module find error

packages/data-wizard/__tests__/dataset/data-frame.test.ts, packages/data-wizard/src/dataset/data-frame.ts
You can use extra.columns to slice data during constructing. The feature only works for (2D) object in array.
Be like
```
const df = new DataFrame([
{ a: 1, b: 4, c: 7 },
{ a: 2, b: 5, c: 8 },
{ a: 3, b: 6, c: 9 },
], { columns: ['a', 'c'] });
```
=> feat(DW): allow slice during constructing

package.json, packages/auto-chart/package.json, packages/chart-advisor/package.json, packages/ckb/__tests__/pack.test.ts, packages/ckb/package.json, packages/data-wizard/__tests__/dataset/data-frame.test.ts, packages/data-wizard/__tests__/dataset/series.test.ts, packages/data-wizard/package.json, packages/data-wizard/src/dataset/base-frame.ts, packages/data-wizard/src/dataset/data-frame.ts, packages/data-wizard/src/dataset/series.ts, packages/data-wizard/src/dataset/types.ts, packages/data-wizard/src/dataset/utils.ts, packages/lite-insight/package.json, packages/smart-board/package.json
Support data conversion by specified data type, and add related test cases. Resolved #381.
Use the `extra.columnTypes` to convert the original data, and its value could be anyone of `TypeSpecifics ('null' | 'boolean' | 'integer' | 'float' | 'date' | 'string')`. The `extra.columnTypes` is an array mapped to `columns`. If you need original data type, the column type could be specified as `''`.
In addition, the issue fixes CKB's `pack.test.ts` and adds jest in pre-commit.
=> feat(dw): support data conversion by specified data type

packages/smart-board/package.json
fix:
```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @antv/smart-board@2.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!   node_modules/@ant-design/icons
npm ERR!     @ant-design/icons@"^4.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0" from react-dom@18.0.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">=16.0.0" from @ant-design/icons@4.7.0
npm ERR!   node_modules/@ant-design/icons
npm ERR!     @ant-design/icons@"^4.7.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! …
```
=> chore(SB): fix peer dep

packages/data-wizard/__tests__/random/case.test.ts, packages/data-wizard/src/analyzer/is-date.ts, packages/data-wizard/src/random/basic-random.ts
If seed is undefined, the package [`mersenne-twister` uses `new Date().getTime()` as seed](https://github.com/boo1ean/mersenne-twister/blob/master/src/mersenne-twister.js#L69). However, the timestamps may be the same, such as [generating random data in a loop](https://github.com/antvis/AVA/pull/403/files#diff-ea92f661b76daa59687874b3ae571db17c4d99b01e038d880562e746c0f47304R5-R14).
The PR [create a random number as seed](https://github.com/antvis/AVA/pull/403/files#diff-ba90428a529645ccc799ea4ce08071d7ca645d7c6027bf13fbb68139e4480535R70) when the seed is undefined to avoid the case that timestamps are the same.
=> feat(dw): create a unique seed to avoid duplicate timestamps causing random data

packages/auto-chart/README.md, packages/auto-chart/zh-CN/README.zh-CN.md, packages/chart-advisor/README.md, packages/chart-advisor/zh-CN/README.zh-CN.md, packages/data-wizard/README.md, packages/data-wizard/zh-CN/README.zh-CN.md, packages/lite-insight/README.md, packages/lite-insight/zh-CN/README.zh-CN.md, packages/smart-board/README.md, packages/smart-board/zh-CN/README.zh-CN.md
Fix the Chinese and English README.md file paths of AutoChart, ChartAdvisor, DataWizard, LiteInsight and SmartBoard.
=> docs: fix readme path

README.md, packages/auto-chart/README.md, packages/auto-chart/zh-CN/README.zh-CN.md, packages/chart-advisor/README.md, packages/chart-advisor/zh-CN/README.zh-CN.md, packages/ckb/README.md, packages/smart-board/README.md, packages/smart-board/zh-CN/README.zh-CN.md, sites/ava-site/docs/guide/auto-chart/intro.en.md, sites/ava-site/docs/guide/auto-chart/intro.zh.md, sites/ava-site/docs/guide/chart-advisor/intro.en.md, sites/ava-site/docs/guide/chart-advisor/intro.zh.md, sites/ava-site/docs/guide/smart-board/intro.en.md, sites/ava-site/docs/guide/smart-board/intro.zh.md, sites/ava-site/examples/chart-advisor/advise-and-lint/API.en.md, sites/ava-site/examples/chart-advisor/advise-and-lint/API.zh.md, sites/ava-site/examples/components/auto-chart/API.en.md, sites/ava-site/examples/components/auto-chart/API.zh.md, sites/ava-site/examples/smart-board/basic/API.en.md, sites/ava-site/examples/smart-board/basic/API.zh.md
Correct invalid api reference links, including:
- links in guides
- links in examples
- others
=> fix: correct api reference links

sites/ava-site/gatsby-node.js, sites/ava-site/package.json
This PR can resolve website build failed issue caused by LI Web Workers. The reason for the issue is that webpack 4 does not support `import.meta.url`. But, how did it work before?
=> chore(site): li import.meta.url in webpack 4 causes build failed

package.json, packages/ava/src/__tests__/data/utils/common.test.ts, packages/ava/src/__tests__/data/utils/isType/isDateString.test.ts, packages/ava/src/__tests__/data/utils/isType/isType.test.ts, packages/ava/src/data/utils/common.ts, packages/ava/src/data/utils/index.ts, packages/ava/src/data/utils/isType/constants.ts, packages/ava/src/data/utils/isType/index.ts, packages/ava/src/data/utils/isType/isDateString.ts
Add utils used internally by ava.
Some utils might be moved to `ava/utils` after careful consideration. We have already had this idea in the [prev PR](https://github.com/antvis/AVA/pull/477/files#r1019152354).
=> refactor(ava/data): migrate and improve utils

package.json, packages/ava-react/package.json, packages/ava-react/rollup.config.js, packages/ava-react/tsconfig.json, packages/ava/package.json, packages/ava/rollup.config.js, rollup.config.js, tsconfig.json
- use separately rollup config to build ts and react pkg;
- init ava-react repo package.json;
- add chart id to avoid types error;
=> chore: optimize ava-react rollup config

packages/ava/package.json, packages/ava/src/advisor/advise-pipeline/advicesForChart.ts, packages/ava/src/advisor/advise-pipeline/data-to-advices.ts, packages/ava/src/advisor/advise-pipeline/spec-mapping.ts, packages/ava/src/advisor/advisor.ts, packages/ava/src/advisor/lint-pipeline/check-rules.ts, packages/ava/src/advisor/lint-pipeline/lintRules.ts, packages/ava/src/advisor/ruler/type.ts, packages/ava/src/advisor/ruler/utils.ts, packages/ava/src/advisor/types.ts, packages/ava/src/advisor/utils/computeScore.ts, packages/ava/src/ckb/index.ts, packages/ava/src/ckb/types.ts, packages/ava/src/data/analysis/field/index.ts, packages/ava/src/data/index.ts, packages/ava/src/index.ts, packages/ava/src/insight/insights/checkers.ts, packages/ava/src/insight/insights/extractors/categoryOutlier.ts, packages/ava/src/insight/insights/extractors/lowVariance.ts, packages/ava/src/insight/insights/extractors/timeSeriesOutlier.ts, packages/ava/src/insight/insights/util.ts
- add full `data` exports
- `import type { CkbTypes }` instead of `import type { XxxType }`  in internal files
- `import { xxx }` from the root of each module   in internal files
=> refactor(ava): improve imports and exports related to ckb and data

packages/ava-react/common/styles/index.less, packages/ava-react/src/InsightCard/InsightCard.tsx, packages/ava-react/src/InsightCard/Title/index.tsx, packages/ava-react/src/InsightCard/Toolbar/constants.ts, packages/ava-react/src/InsightCard/Toolbar/defaultTools.tsx, packages/ava-react/src/InsightCard/Toolbar/index.less, packages/ava-react/src/InsightCard/Toolbar/index.tsx, packages/ava-react/src/InsightCard/Toolbar/types.ts, packages/ava-react/src/InsightCard/constants.tsx, packages/ava-react/src/InsightCard/index.less, packages/ava-react/src/InsightCard/index.ts, packages/ava-react/src/InsightCard/ntvPlugins/components/ChartCarousel.tsx, packages/ava-react/src/InsightCard/ntvPlugins/components/G2Chart.tsx, packages/ava-react/src/InsightCard/ntvPlugins/constants.ts, packages/ava-react/src/InsightCard/ntvPlugins/index.ts, packages/ava-react/src/InsightCard/ntvPlugins/plugins/chartPlugin.tsx, packages/ava-react/src/InsightCard/ntvPlugins/types.ts, packages/ava-react/src/InsightCard/types.ts, packages/ava-react/src/InsightCard/utils/patternsGenerator.ts, packages/ava-react/src/InsightCard/utils/specGenerator.ts, packages/ava-react/src/index.ts, playground/package.json, playground/src/DevPlayground/LiteInsight/AutoInsight.tsx, playground/src/DevPlayground/LiteInsight/mockSpec.ts
- adjust insight card api: group props of insight data as `insightInfo`
- support generate spec using `visualizationSpec` insight info 
- support render custom spec in insight card
=> feat(ava-react/insight-card): support render custom spec in insight card

packages/ava/__tests__/unit/advisor/ruler/rule-cases/aggregation-single-row.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/all-can-be-table.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/diff-pie-sector.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/landscape-or-portrait.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/limit-series.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/no-redundant-field.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/series-qty-limit.test.ts, packages/ava/__tests__/unit/advisor/ruler/rule-cases/x-axis-line-fading.test.ts, packages/ava/src/advisor/ruler/rules/all-can-be-table.ts, packages/ava/src/advisor/ruler/types.ts
=> test: add several lint rules' test

packages/ava-react/src/InsightCard/InsightCard.tsx, packages/ava-react/src/InsightCard/Toolbar/constants.ts, packages/ava-react/src/InsightCard/Toolbar/defaultTools.tsx, packages/ava-react/src/InsightCard/constants.tsx, packages/ava-react/src/InsightCard/index.ts, packages/ava-react/src/InsightCard/ntvPlugins/components/G2Chart.tsx
- support copy insight content and spec 卡片上支持复制能力
- support g2 canvas size change according to container size 支持卡片中图表画布大小响应容器变化
=> feat(ava-react/insight-card): support copy insight result & canvas size change

packages/ava-react/src/InsightCard/ntvPlugins/components/G2Chart.tsx
更新 G2 后，调用 `chart.render()` 时，如果第一次 render 没有结束就调用了第二次，会渲染错误
- 之前由于 G2 不支持 auto size, 在容器大小改变时，重新 render，导致了初始化时多次 render 。去掉这部分逻辑后可以正常展示
- stric mode 下 useEffect 会被执行两次 因此加一个 isRendering 状态，限制渲染中不能更新
=> fix(ava-react/insight-card): fix g2 chart render

packages/ava-react/src/InsightCard/InsightCard.tsx
=> fix(avar-react/insight-card): Add miss dependency when generate contentSpec

commitlint.config.js
We need use '/' as the module separator. However, [commitlint use '/' for multiple scopes](https://github.com/conventional-changelog/commitlint/blob/master/docs/concepts-commit-conventions.md#multiple-scopes). So we add a plugin modified from [commitlint scope-enum source code](https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/rules/src/scope-enum.ts).
=> chore(global): add custom-scope-enum commitlint plugin

packages/ava-react/src/InsightCard/InsightCard.tsx, packages/ava-react/src/InsightCard/ntvPlugins/components/G2Chart.tsx, packages/ava-react/src/InsightCard/types.ts
1.insight content  should be updated whether the insight info is empty or not
2.when using `chart.options` to update spec, the new spec will be merged into the old one, but in InsightCard, the new spec should override the old one, so  the `clear` method should be called before update
before:
after:
=> fix(ava-react/insight-card): fix insight content & chart not update correctly

packages/ava/src/insight/narrative/strategy/changePoint.ts
the origin time range is:
after fix:
=> fix(ava/insight): fix time range of change point in narrative strategy

packages/ava-react/package.json, packages/ava-react/src/NarrativeTextVis/styled/paragraph.tsx, packages/ava/src/ntv/schema/phrase.ts, playground/src/DevPlayground/NTV/index.tsx, site/examples/ntv/basic/demo/extra-phrases.tsx
=> fix(ava,ava-react): ntv text phrase support start space of line

packages/ava/__tests__/unit/insight/extractors/category-outlier.test.ts, packages/ava/__tests__/unit/insight/extractors/change-point.test.ts, packages/ava/__tests__/unit/insight/extractors/correlation.test.ts, packages/ava/__tests__/unit/insight/extractors/low-variance.test.ts, packages/ava/__tests__/unit/insight/extractors/majority.test.ts, packages/ava/__tests__/unit/insight/extractors/time-series-outlier.test.ts, packages/ava/__tests__/unit/insight/extractors/trend.test.ts, packages/ava/src/data/statistics/constants.ts, packages/ava/src/data/statistics/pcorrtest.ts, packages/ava/src/data/statistics/types.ts, packages/ava/src/insight/constant.ts, packages/ava/src/insight/insights/checkers.ts, packages/ava/src/insight/insights/extractors/categoryOutlier.ts, packages/ava/src/insight/insights/extractors/changePoint.ts, packages/ava/src/insight/insights/extractors/correlation.ts, packages/ava/src/insight/insights/extractors/lowVariance.ts, packages/ava/src/insight/insights/extractors/majority.ts, packages/ava/src/insight/insights/extractors/timeSeriesOutlier.ts, packages/ava/src/insight/insights/extractors/trend.ts, packages/ava/src/insight/insights/index.ts, packages/ava/src/insight/insights/util.ts, packages/ava/src/insight/pipeline/extract.ts, packages/ava/src/insight/types.ts
改造insightExtractors方法，支持指定insightType，获取单个算子的结论，用法如下
```ts
const trendInsights = insightExtractor({
data,
measures,
dimensions,
insightType: 'trend',
}) 
```
已更新测试用例 并通过
=> feat(ava/insight): support calling algorithms individually

packages/ava/__tests__/unit/insight/extractors/category-outlier.test.ts, packages/ava/__tests__/unit/insight/extractors/change-point.test.ts, packages/ava/__tests__/unit/insight/extractors/low-variance.test.ts, packages/ava/__tests__/unit/insight/extractors/majority.test.ts, packages/ava/__tests__/unit/insight/extractors/time-series-outlier.test.ts, packages/ava/__tests__/unit/insight/extractors/trend.test.ts, packages/ava/src/index.ts, packages/ava/src/insight/constant.ts, packages/ava/src/insight/index.ts, packages/ava/src/insight/insights/extractors/categoryOutlier.ts, packages/ava/src/insight/insights/extractors/changePoint.ts, packages/ava/src/insight/insights/extractors/lowVariance.ts, packages/ava/src/insight/insights/extractors/majority.ts, packages/ava/src/insight/insights/extractors/timeSeriesOutlier.ts, packages/ava/src/insight/insights/extractors/trend.ts, packages/ava/src/insight/insights/util.ts, packages/ava/src/insight/pipeline/extract.ts, packages/ava/src/insight/pipeline/insight.ts, packages/ava/src/insight/pipeline/specificInsight.ts, packages/ava/src/insight/types.ts
=> feat(ava/insight): generate marks of a specific insight type

packages/ava/src/insight/chart/strategy/commonMarks/pointMark.ts, packages/ava/src/insight/insights/util.ts, packages/ava/src/insight/pipeline/specificInsight.ts, packages/ava/src/insight/types.ts
=> fix(ava/insight): only generate annotationSpec for valid patternInfo

packages/ava/package.json, packages/ava/src/index.ts, packages/ava/src/insight/chart/generator/insights.ts, packages/ava/src/insight/chart/index.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/categoryOutlier.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/changePoint.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/index.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/lowVariance.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/timeSeriesOutlier.ts, packages/ava/src/insight/chart/strategy/augmentedMarks/trend.ts, packages/ava/src/insight/chart/strategy/commonMarks/pointMark.ts, packages/ava/src/insight/chart/types.ts, packages/ava/src/insight/chart/utils.ts, packages/ava/src/insight/index.ts, packages/ava/src/insight/insights/util.ts, packages/ava/src/insight/pipeline/specificInsight.ts, packages/ava/src/insight/types.ts
=> feat(ava/insight): optimize insight marks

packages/ava/src/data/analysis/field/index.ts
当数据是 ["32", "1980", "43" ] 会死循环
=> fix(insight): 修复 同时命中 Integer 与 Date 类型时，死循环问题

packages/ava/__tests__/unit/data/utils/isType/isDateString.test.ts, packages/ava/src/advisor/advise-pipeline/advicesForChart.ts, packages/ava/src/data/utils/isType/constants.ts, packages/ava/src/data/utils/isType/isDateString.ts
PR #749 中提到需要在绘制折线图等横轴为时间的图表时，将识别为日期字段的数据转换为标准日期格式传入 G2 spec 中，但`new Date()` 的生效范围和 `ava/data` 中识别日期的方式不一致， 因此提供一个函数使用和识别日期格式相同的正则来解析日期字符串。
#749 try to parse date string to js `Date` by `new Date()` when draw line chart, but some date string like '1996-W08' cannot be parsed by `new Date()`. So `data` provide a tool function to parse ISO 8601 date string to Date, using the same regular expressions that has been used for filed type recommendation.
=> feat(ava/data): add function to parse ISO date string to js Date type

packages/ava-react/package.json, packages/ava-react/src/NarrativeTextVis/phrases/Phrase.tsx
=> fix(ava-react/ntv): fix ntv default text

packages/ava/__tests__/unit/data/analysis/field/index.test.ts, packages/ava/src/data/analysis/field/index.ts
YYYY.M 格式的数据也会被识别为 日期。导致 某数值列 的推荐类型 有float和date，出现死循环
=> fix(ava/data): fix the infinite loop issue in analyzeField
